# Generated by Django 5.0.6 on 2024-06-04 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0002_image_postcategory_reactioncategory_comment_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactioncategory',
            name='reaction_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_social.profile'),
        ),
    ]
