# Generated by Django 5.0.6 on 2024-06-04 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0004_remove_posts_post_image_posts_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reactioncategory',
            old_name='reaction',
            new_name='reaction_type',
        ),
        migrations.RemoveField(
            model_name='reactioncategory',
            name='reaction_author',
        ),
        migrations.AlterField(
            model_name='posts',
            name='comments',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_social.comment'),
        ),
        migrations.RemoveField(
            model_name='posts',
            name='reactions',
        ),
        migrations.CreateModel(
            name='PostSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_sub_category', models.CharField(max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_social.postcategory')),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='post_sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_social.postsubcategory'),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_social.reactioncategory')),
                ('reaction_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_social.profile')),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='reactions',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_social.reaction'),
        ),
    ]
