# Generated by Django 5.0.6 on 2024-06-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0005_rename_reaction_reactioncategory_reaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
