# Generated by Django 5.0.6 on 2024-06-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0006_alter_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image_caption',
            field=models.TextField(default=None, null=True),
        ),
    ]
