# Generated by Django 5.0.6 on 2024-06-06 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0008_alter_posts_image_alter_posts_image_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsubcategory',
            name='category',
        ),
    ]
