# Generated by Django 5.0.6 on 2024-06-06 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0009_remove_postsubcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_social.comment'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image_caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='reactions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_social.reaction'),
        ),
    ]
